### ISSUE TITLE
multiple processes sending logging messages to Qt’s dialog box on MacOS

### ISSUE THREAD

**Issue by davemfish** [natcap/pygeoprocessing#18] opened 2020-01-09 00:08 UTC
There's an issue detailed over at https://bitbucket.org/natcap/invest/issues/3931/invest-370-sdr-crashes-hard-on-mac, which seems to boil down to multiple processes started by pygeoprocessing sending logging messages to Qt’s dialog box on MacOS. 

Pygeoprocessing does not use any type of Queue handler for logging, and it does use multiprocessing by default in some operations such as `align_and_resize`. Presumably a queue handler for the logger would resolve this and be generally a good idea, even though this problem only occurs in one very specific instance (that we know of).

```
natcap.invest.sdr.sdr 3.7.0.post839+h89ab3f9d1349
pygeoprocessing 1.9.1
MacOS 10.15.2 (Catalina)
```

```
01/08/2020 15:57:47  pygeoprocessing.geoprocessing INFO     starting stats_worker
The process has forked and you cannot use this CoreFoundation functionality safely. You MUST exec().
Break on __THE_PROCESS_HAS_FORKED_AND_YOU_CANNOT_USE_THIS_COREFOUNDATION_FUNCTIONALITY___YOU_MUST_EXEC__() to debug.
The process has forked and you cannot use this CoreFoundation functionality safely. You MUST exec().
Break on __THE_PROCESS_HAS_FORKED_AND_YOU_CANNOT_USE_THIS_COREFOUNDATION_FUNCTIONALITY___YOU_MUST_EXEC__() to debug.
The process has forked and you cannot use this CoreFoundation functionality safely. You MUST exec().
Break on __THE_PROCESS_HAS_FORKED_AND_YOU_CANNOT_USE_THIS_COREFOUNDATION_FUNCTIONALITY___YOU_MUST_EXEC__() to debug.
Fatal Python error: Illegal instruction

Current thread 0x000070000d4de000 (most recent call first):
  File "env/lib/python3.7/site-packages/natcap/invest/ui/inputs.py", line 291 in write
  File "env/lib/python3.7/logging/__init__.py", line 1028 in emit
  File "env/lib/python3.7/logging/__init__.py", line 894 in handle
  File "env/lib/python3.7/logging/__init__.py", line 1586 in callHandlers
  File "env/lib/python3.7/logging/__init__.py", line 1524 in handle
  File "env/lib/python3.7/logging/__init__.py", line 1514 in _log
  File "env/lib/python3.7/logging/__init__.py", line 1378 in info
  File "env/lib/python3.7/site-packages/pygeoprocessing/geoprocessing.py", line 377 in raster_calculator
  File "env/lib/python3.7/site-packages/pygeoprocessing/geoprocessing.py", line 3120 in mask_raster
  File "env/lib/python3.7/site-packages/pygeoprocessing/geoprocessing.py", line 2002 in warp_raster
  File "env/lib/python3.7/multiprocessing/pool.py", line 121 in worker
  File "env/lib/python3.7/multiprocessing/process.py", line 99 in run
  File "env/lib/python3.7/multiprocessing/process.py", line 297 in _bootstrap
  File "env/lib/python3.7/multiprocessing/popen_fork.py", line 74 in _launch
  File "env/lib/python3.7/multiprocessing/popen_fork.py", line 20 in __init__
  File "env/lib/python3.7/site-packages/PyInstaller/loader/rthooks/pyi_rth_multiprocessing.py", line 71 in __init__
  File "env/lib/python3.7/multiprocessing/context.py", line 277 in _Popen
  File "env/lib/python3.7/multiprocessing/process.py", line 112 in start
  File "env/lib/python3.7/multiprocessing/pool.py", line 241 in _repopulate_pool
  File "env/lib/python3.7/multiprocessing/pool.py", line 248 in _maintain_pool
  File "env/lib/python3.7/multiprocessing/pool.py", line 412 in _handle_workers
  File "env/lib/python3.7/threading.py", line 870 in run
  File "env/lib/python3.7/threading.py", line 926 in _bootstrap_inner
  File "env/lib/python3.7/threading.py", line 890 in _bootstrap
```

**Comment by davemfish** [comment] 2020-01-12 19:39
We decided that a good solution here is to remove the `multiprocessing.Pool` entirely from `align_and_resize_raster_stack`, which is the only instance of a process pool in pygeoprocessing. 

Some parallelization is still possible at the `gdal.Warp` level by passing `gdal_warp_options` to `align_and_resize...`. And more control over parallelization can happen at a higher level, with individual calls to `warp_raster` instead of one call to `align_and_resize`.

**Comment by phargogh** [comment] 2020-01-25 01:37
I'll close this issue since it was merged a while ago.  Feel free to reopen if desired!

**Closed as completed by phargogh** 2020-01-25 01:37 UTC
Labels: bug

**Comment by richpsharp** [comment] 2020-08-06 21:14
FYI we mention above that passing `n_threads` to `gdal.Warp` is an option for gdal level parallelism. I have found that parameter to be flaky in practice in the sense that only one of the `n` threads seems to write results to the file in cases that are difficult to reproduce. So flaky I'd plan to remove this feature in a future version of pygeoprocessing.
